// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import lit from 'eslint-plugin-lit';
import wc from 'eslint-plugin-wc';
import playwright from 'eslint-plugin-playwright';
import importX from 'eslint-plugin-import-x';
import prettier from 'eslint-config-prettier';

/**
 * Lint configuration for the whole workspace, run in a single pass from the root.
 *
 * ── Why the root pins TypeScript 5.x while every package builds with 7.x ──
 *
 * TypeScript 7 is the native (Go) compiler. It deliberately does not ship the
 * legacy JavaScript compiler API: `require('typescript')` resolves to
 * `lib/version.cjs`, and there is no `createSourceFile`, `createProgram` or
 * `SyntaxKind`. The new API lives behind `typescript/unstable/*` and is a
 * different surface entirely.
 *
 * typescript-eslint targets the legacy API, so it cannot even *parse* with
 * TypeScript 7 — this is not just a loss of type-aware rules. The fix is that
 * the repo root declares `typescript: ^5.9`, used only by this linter, while
 * every workspace package keeps `typescript: catalog:` (7.x) for its build.
 * pnpm's isolated layout keeps the two apart; `pnpm run typecheck` and
 * `pnpm run build` still go through Turbo to each package's own 7.x compiler.
 *
 * Do not "tidy" the root TypeScript back to `catalog:` — linting stops working.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/.tmp/**',
      'packages/ui/custom-elements.json',
      // Generated by build-styles.mjs / build-icons.mjs; not hand-edited.
      'packages/ui/src/styles/generated.ts',
      'packages/ui/src/icons/generated.ts',
      // Playwright output.
      '**/playwright-report/**',
      '**/test-results/**',
      'e2e/**/*-snapshots/**',
      // Vendored third-party skill content.
      '.claude/skills/humanizer/**',
    ],
  },

  // ── Plain JS / ESM scripts: no type information available or needed ────────
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { process: 'readonly', console: 'readonly', URL: 'readonly' },
    },
  },

  // ── TypeScript, type-aware ────────────────────────────────────────────────
  {
    files: ['**/*.ts'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
      wc.configs['flat/recommended'],
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    /**
     * Only import-x's two ordering rules are enabled, deliberately.
     *
     * Its `recommended`/`typescript` presets bring correctness rules
     * (`namespace`, `default`, `export`, `no-unresolved`) that all need full
     * module resolution. That resolution cannot work reliably here: `apps/api`
     * imports `./config.ts` under `allowImportingTsExtensions`, while every
     * library imports `./x.js` specifiers that actually point at `.ts` sources.
     * Worse, `flatConfigs.typescript` registers a resolver interface import-x v4
     * rejects outright ("invalid interface loaded as resolver"), which turns
     * every file into a false positive.
     *
     * tsc already checks all of that, and checks it properly. The ordering rules
     * are the part tsc does not do, so they are the part worth keeping.
     */
    plugins: { 'import-x': importX },
    rules: {
      // `verbatimModuleSyntax` is on, so type-only imports must be explicit.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],

      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'never',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import-x/no-duplicates': 'error',

      // Unused args are usually a signal here, but an underscore prefix is the
      // conventional way to say "required by the signature, deliberately unused".
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },

  // ── Lit components ────────────────────────────────────────────────────────
  {
    files: ['packages/ui/src/**/*.ts', 'apps/web/src/**/*.ts'],
    extends: [lit.configs['flat/recommended']],
    rules: {
      /**
       * False positive on every Lit event binding.
       *
       * `@click=${this.toggle}` looks like an unbound method reference, but Lit
       * invokes event listeners with `this` set to the host element, so the
       * binding is correct. Rewriting these as arrow functions would be strictly
       * worse: a fresh closure per render defeats Lit's listener diffing and
       * removes/re-adds the listener on every update.
       */
      '@typescript-eslint/unbound-method': 'off',
    },
  },

  /**
   * The purity guarantee of the attribution engine, enforced mechanically.
   *
   * `@dwc/diagnostics` consumes evidence and produces verdicts. It must have no
   * I/O, no network and — the easy one to break by accident — no clock and no
   * randomness. That is what makes the verdict logic testable against fixtures
   * instead of against the live internet, and what makes a stored report
   * reproducible. A comment asking people not to call `Date.now()` is not a
   * guarantee; this is.
   *
   * Timestamps belong to the caller: the API stamps reports, the engine is told.
   */
  {
    files: ['packages/diagnostics/src/**/*.ts'],
    ignores: ['packages/diagnostics/src/**/*.test.ts'],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'Date',
          property: 'now',
          message:
            'The attribution engine must stay pure and deterministic. Take the timestamp as an argument instead.',
        },
        {
          object: 'Math',
          property: 'random',
          message:
            'The attribution engine must stay deterministic — the same evidence must always yield the same verdict.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'NewExpression[callee.name="Date"]',
          message:
            'The attribution engine must stay pure. Accept a timestamp as an argument rather than reading the clock.',
        },
        {
          selector: 'CallExpression[callee.object.name="performance"][callee.property.name="now"]',
          message: 'The attribution engine must stay pure — no clock access.',
        },
      ],
    },
  },

  /**
   * Decorators are a build-breaking mistake in the app layer, so they are banned
   * outright rather than left to be rediscovered.
   *
   * Vite 8 transforms with Oxc, which cannot lower decorators of either flavour
   * (standard or TypeScript-experimental). A decorated class in `apps/web`
   * therefore reaches the browser verbatim and dies with
   * "Unexpected token 'export'" — a blank page, with nothing in the build output
   * to suggest why. This exact bug already cost real debugging time once.
   *
   * `packages/ui` is deliberately exempt: tsc compiles it ahead of time, so
   * consumers only ever receive plain JavaScript.
   */
  {
    files: ['apps/web/src/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Decorator',
          message:
            "Vite's Oxc transform cannot lower decorators, so this reaches the browser as invalid syntax and renders a blank page. Use Lit's static `properties` API here instead.",
        },
      ],
    },
  },

  // ── Tests: allow the pragmatism that test code needs ──────────────────────
  {
    files: ['**/*.test.ts', '**/*.spec.ts', 'packages/fixture-server/src/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      // Fixtures and tests legitimately need a clock and fake data.
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  // ── Playwright specs ──────────────────────────────────────────────────────
  {
    files: ['e2e/**/*.spec.ts'],
    extends: [playwright.configs['flat/recommended']],
    rules: {
      /**
       * Platform and project gating is a legitimate use of `.skip()`.
       *
       * Visual baselines are committed for Linux only (font rasterisation differs
       * per platform), and the mobile drawer does not exist above the desktop
       * breakpoint. Skipping in those cases is correct; the rule cannot tell that
       * apart from a test someone disabled and forgot.
       */
      'playwright/no-skipped-test': ['warn', { allowConditional: true }],

      // The a11y specs assert inside a shared `audit()` helper so a failure can
      // print the offending rule and element; without this the rule reads them as
      // assertion-free.
      // Helpers that assert on the caller's behalf. Without these the rule
      // flags a test whose assertions live one function call away.
      'playwright/expect-expect': ['warn', { assertFunctionNames: ['audit', 'noOverflow'] }],
    },
  },

  // The CLI's whole purpose is printing to stdout.
  {
    files: ['apps/api/src/cli/**/*.ts', '**/scripts/**/*.mjs'],
    rules: { 'no-console': 'off' },
  },

  // Must stay last: turns off every rule Prettier owns, so the two never fight.
  prettier,
);
