/**
 * Compile Tailwind once, then wrap the output in a TypeScript module.
 *
 * Why codegen rather than importing the CSS directly: this package is built with
 * plain `tsc`, not a bundler, so there is no `?inline` import to lean on. Turning
 * the compiled sheet into a `.ts` file keeps the library free of any bundler
 * requirement — consumers can use Vite, webpack, or nothing at all.
 *
 * The result is a single exported string. `styles/shared.ts` wraps it in one
 * `unsafeCSS` instance, so every component adopts the *same* CSSStyleSheet object
 * by reference rather than each parsing its own copy.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const input = join(root, 'src/styles/tailwind.css');
const temp = join(root, '.tmp/tailwind.built.css');
const output = join(root, 'src/styles/generated.ts');

mkdirSync(dirname(temp), { recursive: true });

// Resolve the CLI's real JS entry point rather than the node_modules/.bin shim.
// Node refuses to spawn a .CMD directly (EINVAL) without a shell, and going
// through a shell would mean quoting paths differently per platform.
const require = createRequire(import.meta.url);
const manifestPath = require.resolve('@tailwindcss/cli/package.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const binField = manifest.bin;
const relativeBin = typeof binField === 'string' ? binField : binField.tailwindcss;
const cliEntry = join(dirname(manifestPath), relativeBin);

execFileSync(process.execPath, [cliEntry, '-i', input, '-o', temp, '--minify'], {
  stdio: ['ignore', 'ignore', 'inherit'],
  cwd: root,
});

const css = readFileSync(temp, 'utf8');

// Escape only what would break a template literal. The CSS itself is ours, but
// Tailwind emits content:"\\" style escapes that must survive verbatim.
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

writeFileSync(
  output,
  `// GENERATED by scripts/build-styles.mjs — do not edit.\n` +
    `// Compiled Tailwind output, shared by reference across every shadow root.\n` +
    `export const TAILWIND_CSS = \`${escaped}\`;\n`,
  'utf8',
);

console.error(`build-styles: ${String(Math.round(css.length / 1024))} KB → src/styles/generated.ts`);
